In [2]:
import numpy as np 

##2 Dimensional Array##

In [5]:
myarray = np.array([[1,0,0],[1,0,"1"]],dtype='float64')

myarray

array([[1., 0., 0.],
       [1., 0., 1.]])

In [31]:

y = np.array([3+4j, 0.4+7.8j])
print(y.dtype)
n = [[-1, -2, -3, -4], [-2,-4, -6, -8]]

x= np.array(n)
print(x.ndim,"\n",x.shape,"\n",x.size)

complex128
2 
 (2, 4) 
 8


By Using List 


In [36]:
n = [5, 10, 15, 20, 25]

a =  [
    [4.1, 2.5], [1.1, 2.3], [9.1, 2.5], 
     [8.6, 9.9],[3.6, 4.3], [6.6, 0.3]
]

x = np.array(a, dtype='float64')

type(x), x.ndim, x.shape

(numpy.ndarray, 2, (6, 2))

In [38]:
x = np.full(shape=(2,4),fill_value='a')
print(x)

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [40]:
x= np.arange(3,30,3)
x

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [70]:
y = np.linspace(3, 15, 5 ,endpoint=False, retstep=True, dtype=None) # 5 is size of array 'y'
print(y)
print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

(array([ 3. ,  5.4,  7.8, 10.2, 12.6]), 2.4)
[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [60]:

np.random.seed(100)
x = np.random.ranf(3)
x

array([0.54340494, 0.27836939, 0.42451759])

In [64]:
np.random.seed(100)
x = np.random.randn(3,2,4) # Standard normal distribution

print(x)

[[[-1.74976547  0.3426804   1.1530358  -0.25243604]
  [ 0.98132079  0.51421884  0.22117967 -1.07004333]]

 [[-0.18949583  0.25500144 -0.45802699  0.43516349]
  [-0.58359505  0.81684707  0.67272081 -0.10441114]]

 [[-0.53128038  1.02973269 -0.43813562 -1.11831825]
  [ 1.61898166  1.54160517 -0.25187914 -0.84243574]]]


In [69]:
from io import StringIO

y=  StringIO('''
1,2,3,4,5,6,7,3,4,2,2,8,8,9,0,10
''')

x= np.loadtxt(y,delimiter=',')
x
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
