In [2]:
import numpy as np

In [5]:
x =np.full(shape=(3,2,2),fill_value=1)
y=3*np.eye(3)
x

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [5]:
x= np.random.rand(10,50,6)

In [11]:
x= np.arange(2,42,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [19]:
np.random.seed(100)
x = np.random.randint(10, 100, 8)
print(x, end='\n\n')
z = x.reshape(2,2,3)
print(z, '\n\n')

[18 34 77 97 89 58 20 62]



ValueError: cannot reshape array of size 8 into shape (2,2,3)

In [20]:
x=np.linspace(10,20,30)
x

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [9]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z=np.vstack((x,y))
np.vstack((z,x,y))

np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [8]:

x = np.arange(36).reshape(6, 6)
print(x)
res = np.hsplit(x, 2)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [47]:

x = np.arange(4).reshape(2,2)

y = np.vsplit(x,2)
print(y[0])

[[0 1]]


In [36]:
x= np.array([3,6,9,12])
y= np.array([15, 18, 21, 24])
z=np.vstack((x,y))


[array([[ 3,  6,  9, 12]]), array([[15, 18, 21, 24]])]